spring:
  application:
    name: MoviesDownloader

telegram:
  bot:
    token: ${BOT_TOKEN:8772297549:AAESp0BoaZOGInXCIp_D_4A_oGZ04duNbe8}
    username: ${BOT_USERNAME:AnastasiyaKPT2Bot}
    webhook-path: ""  # Оставляем пустым для Long Polling

logging:
  level:
    com.example.bot: DEBUG
    org.telegram: INFO