spring:
  application:
    name: MoviesDownloader

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    com.example.bot: DEBUG
    org.telegram: INFO